### ISSUE TITLE
docker logout throws error on MacOS

### ISSUE THREAD

**Issue by adal-io** [docker/docker-credential-helpers#59]
Docker Version 17.03.1-ce-mac5 (16048)
MacOS Sierra Version 10.12.4

--------

`docker logout myregistry.example.com:5000` throws warning:

````
Removing login credentials for myregistry.example.com:5000
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.`
````

When running `docker logout myregistry.example.com:5000` again, it is confirmed that the logout was successful:

`Not logged in to myregistry.example.com:5000`

This issue has also been replicated on OSX Yosemite 10.10.5 with a fresh install of Docker CE.

**Comment by andradei** [comment]
Same issue on Docker 17.06.0-ce-rc5-mac16.

**Comment by caitong93** [comment]
Docker Version Version 17.06.0-ce-mac18 (18433)
MacOS 10.11.6

After updated docker, I got `denied: requested access to the resource is denied` when running `docker push`. Then I run `docker logout test-registry.com` (my private registry),  but got
```
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.`
``` 
`docker login test-registry.com` is ok, but the auth info seems not right
cat ~/.docker/config.json
```
{
	"auths": {
		"test-registry.com": {},
	},
	"credsStore": "osxkeychain"
}
```

**Comment by mrotaru** [comment]
Same on El Capitan 10.11.16, Docker version 17.06.0-ce, build 02c1d87 (18432)

Anybody knows the latest version which doesn't have this issue ?

**Comment by mrotaru** [comment]
Re-installed current stable (Version 17.06.0-ce-mac18 (18433)) and not seeing the issue.

**Comment by saliceti** [comment]
Same issue with docker 17.06.1-ce, macos 10.12.6

**Comment by joedragons** [comment]
In case it helps, I was doing some version testing the other day and also noticed this on 1.13.1.  I did not notice this on 1.9.1.

**Comment by ElPsyCongro** [comment]
Same issue with docker Version 17.06.2-ce-mac27(19124), macOS Sierra 10.12.6. I do login into a private registry on another machine on same network; the login is successful but the logout gives me this  "WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.`"

**Comment by liming-gd** [comment]
Same issue on macOS High Sierra 10.13.1 (17B48) and Docker 17.09.0-ce-mac35 (19611).

I fixed it by rebooting my Mac.  See docker/for-mac#2228

**Comment by saqib-ahmed** [comment]
I'm hitting the same issue after deleting some certificates in my keychain.

**Comment by sumitb** [comment]
I'm seeing this error as well with:
Docker version 19.03.1, build 74b1e89
System Version: macOS 10.14.6 (18G87)

I tried restarting mac but that didn't fix the issue for me

**Comment by akiko-pusu** [comment]
Same issue with: Docker version 19.03.2, build 6a30dfc /  macOS 10.14.6.
I saw this issue in case login to the private registry only. 
I can logout from docker.io (default registry) without any warning.

**Comment by Moghi** [comment]
Same issue with CentOS Linux release 8.0.1905 , Docker version 19.03.4, build 9013bf583a

**Comment by Gronis** [comment]
Same issue with MacOS Mojave 10.14.4. Docker desktop 2.1.0.5. Docker engine 19.03.5. Also using private repository.

**Comment by chriswininger** [comment]
Not a solution but I found a workaround on OSX. Open the "Keychain Access" application and delete the entry called Docker Credentials. You are now logged out 🤷

**Comment by Segfaultd** [comment]
Same issue with macOS big sur

**Comment by Seelam-Ramesh-Reddy** [comment]
Same issue.Is there any resolution ?

**Comment by kiwamizamurai** [comment]
Same issue with the following environment

```
❯ sw_vers
ProductName:            macOS
ProductVersion:         13.6
BuildVersion:           22G120

❯ docker --version
Docker version 25.0.3, build 4debf41
````

I use ECR repository.

https://aws.amazon.com/jp/blogs/aws/announcing-pull-through-cache-repositories-for-amazon-elastic-container-registry/
